version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 50201:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
volumes:
  data:
